env_name: water_plant
camera_mapping:  # pi0.5 image name -- env image name
  base: front
  wrist_left: wrist
  wrist_right: wrist
prompt: "Grasp the watering can and apply water to the plant."
robot_type: single_arm
