env_name: bimanual_unlock_ipad
camera_mapping:  # pi0.5 image name -- env image name
  base: ego
  wrist_left: wrist_left
  wrist_right: wrist_right
prompt: "Grasp the iPad and enter the result of 2+2 as the password to unlock the device."
password: [4]
robot_type: dual_arm
